// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// -------------------------------------------------------------------------------

`timescale 1 ps / 1 ps

(* BLOCK_STUB = "true" *)
module axis_interconnect_0 (
  ACLK,
  ARESETN,
  S00_AXIS_ACLK,
  S00_AXIS_ARESETN,
  S00_AXIS_TVALID,
  S00_AXIS_TREADY,
  S00_AXIS_TDATA,
  S00_AXIS_TDEST,
  M00_AXIS_ACLK,
  M01_AXIS_ACLK,
  M00_AXIS_ARESETN,
  M01_AXIS_ARESETN,
  M00_AXIS_TVALID,
  M01_AXIS_TVALID,
  M00_AXIS_TREADY,
  M01_AXIS_TREADY,
  M00_AXIS_TDATA,
  M01_AXIS_TDATA,
  M00_AXIS_TDEST,
  M01_AXIS_TDEST,
  S00_DECODE_ERR
);

  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLKIF CLK" *)
  (* X_INTERFACE_MODE = "slave CLKIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME CLKIF, FREQ_HZ 200000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN , ASSOCIATED_BUSIF , ASSOCIATED_PORT , ASSOCIATED_RESET , INSERT_VIP 0" *)
  input ACLK;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 RSTIF RST" *)
  (* X_INTERFACE_MODE = "slave RSTIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME RSTIF, POLARITY ACTIVE_LOW, INSERT_VIP 0" *)
  input ARESETN;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 S00_CLKIF CLK" *)
  (* X_INTERFACE_MODE = "slave S00_CLKIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S00_CLKIF, FREQ_HZ 200000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN , ASSOCIATED_BUSIF , ASSOCIATED_PORT , ASSOCIATED_RESET , INSERT_VIP 0" *)
  input S00_AXIS_ACLK;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 S00_RSTIF RST" *)
  (* X_INTERFACE_MODE = "slave S00_RSTIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S00_RSTIF, POLARITY ACTIVE_LOW, INSERT_VIP 0" *)
  input S00_AXIS_ARESETN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S00_AXIS TVALID" *)
  (* X_INTERFACE_MODE = "slave S00_AXIS" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME S00_AXIS, TDATA_NUM_BYTES 10, TDEST_WIDTH 1, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN , LAYERED_METADATA undef, INSERT_VIP 0" *)
  input S00_AXIS_TVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S00_AXIS TREADY" *)
  output S00_AXIS_TREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S00_AXIS TDATA" *)
  input [79:0]S00_AXIS_TDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 S00_AXIS TDEST" *)
  input [0:0]S00_AXIS_TDEST;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 M00_CLKIF CLK" *)
  (* X_INTERFACE_MODE = "slave M00_CLKIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M00_CLKIF, FREQ_HZ 200000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN , ASSOCIATED_BUSIF , ASSOCIATED_PORT , ASSOCIATED_RESET , INSERT_VIP 0" *)
  input M00_AXIS_ACLK;
  (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 M01_CLKIF CLK" *)
  (* X_INTERFACE_MODE = "slave M01_CLKIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M01_CLKIF, FREQ_HZ 200000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN , ASSOCIATED_BUSIF , ASSOCIATED_PORT , ASSOCIATED_RESET , INSERT_VIP 0" *)
  input M01_AXIS_ACLK;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 M00_RSTIF RST" *)
  (* X_INTERFACE_MODE = "slave M00_RSTIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M00_RSTIF, POLARITY ACTIVE_LOW, INSERT_VIP 0" *)
  input M00_AXIS_ARESETN;
  (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 M01_RSTIF RST" *)
  (* X_INTERFACE_MODE = "slave M01_RSTIF" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M01_RSTIF, POLARITY ACTIVE_LOW, INSERT_VIP 0" *)
  input M01_AXIS_ARESETN;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M00_AXIS TVALID" *)
  (* X_INTERFACE_MODE = "master M00_AXIS" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M00_AXIS, TDATA_NUM_BYTES 10, TDEST_WIDTH 1, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN , LAYERED_METADATA undef, INSERT_VIP 0" *)
  output M00_AXIS_TVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M01_AXIS TVALID" *)
  (* X_INTERFACE_MODE = "master M01_AXIS" *)
  (* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME M01_AXIS, TDATA_NUM_BYTES 10, TDEST_WIDTH 1, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN , LAYERED_METADATA undef, INSERT_VIP 0" *)
  output M01_AXIS_TVALID;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M00_AXIS TREADY" *)
  input M00_AXIS_TREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M01_AXIS TREADY" *)
  input M01_AXIS_TREADY;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M00_AXIS TDATA" *)
  output [79:0]M00_AXIS_TDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M01_AXIS TDATA" *)
  output [79:0]M01_AXIS_TDATA;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M00_AXIS TDEST" *)
  output [0:0]M00_AXIS_TDEST;
  (* X_INTERFACE_INFO = "xilinx.com:interface:axis:1.0 M01_AXIS TDEST" *)
  output [0:0]M01_AXIS_TDEST;
  (* X_INTERFACE_IGNORE = "true" *)
  output S00_DECODE_ERR;

  // stub module has no contents

endmodule
